swagger: '2.0'
info:
  title: Temperature Reader API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json

paths:
  /sensors:
    get:
      tags: [Sensors]
      operationId: master.get_sensors
      summary: Get temperature readings from all sensors
      responses:
        200:
          description: Return temperature readings
          schema:
            type: array
            items:
              $ref: '#/definitions/Sensor'
  /sensors/history:
    get:
      tags: [Sensors]
      operationId: master.get_sensor_history
      summary: Get the history for a specific day
      responses:
        200:
          description: Return history
          schema:
            $ref: '#/definitions/Sensor'
        404:
          description: No history exists for the given day
  /collect:
      get:
        tags: [Sensors]
        operationId: master.get_collect
        summary: Do a single reading
        responses:
          200:
            description: Reading was successfull
          500:
            description: Reading failed

parameters:
  sensor_id:
    name: sensor_id
    description: Sensors's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"
  history_day:
    name: history_day
    description: A day
    in: path
    type: string
    required: true

definitions:
  Sensor:
    type: object
    required:
      - id
      - temperature
    properties:
      id:
        type: string
        description: Unique identifier
        example: "28-0315a47057ff"
        readOnly: true
      temperature:
        type: number
        description: The temperature
        example: "19.234"
